export interface Vehicle {
    id: number;
    brand: string;
    model: string;
    version: string;
    year: number;
    modelYear: number;
    price: string;
    fuel: string;
    km: string;
    transmission: string;
    color: string;
    image: string;
    features: string[];
    description: string;
    extras?: string[]; // Made optional to match usage
    images?: string[];
    archived?: boolean;
}

export const vehicles: Vehicle[] = [
    {
        id: 1,
        brand: "Volkswagen",
        model: "Gol",
        version: "1.0 Trendline",
        year: 2017,
        modelYear: 2016,
        price: "Consulte",
        fuel: "Flex",
        km: "118.000",
        transmission: "Manual",
        color: "Vermelho",
        image: "/car-hatchback.png",
        features: [
            "Direção Hidráulica",
            "Trava Elétrica",
            "Vidros Elétricos",
            "Ar Condicionado",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo completo com direção hidráulica, trava e vidros elétricos e com ar condicionado.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 2,
        brand: "Volkswagen",
        model: "Fox",
        version: "Extreme 1.6",
        year: 2020,
        modelYear: 2020,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Vermelho",
        image: "/car-hatchback.png",
        features: [
            "Travas Elétricas",
            "Vidros Elétricos",
            "Farol Auxiliar",
            "Farol de Neblina",
            "Direção Hidráulica",
            "Rodas Diamantadas",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo com travas e vidros elétricos, com farol auxiliar e de neblina. Com direção hidráulica e rodas diamantadas.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 3,
        brand: "Renault",
        model: "Sandero",
        version: "Intense 1.6",
        year: 2020,
        modelYear: 2020,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-hatchback.png",
        features: [
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "Bancos Misto Couro/Tecido",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo com direção hidráulica e rodas liga leve. Com bancos misto de couro e tecido.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 4,
        brand: "Fiat",
        model: "Palio",
        version: "EVO Essence 1.6",
        year: 2016,
        modelYear: 2015,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Cinza",
        image: "/car-hatchback.png",
        features: [
            "Travas Elétricas",
            "Vidros Elétricos",
            "Som Original Fiat",
            "Freios ABS",
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "4 Pneus Novos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo com travas e vidros elétricos, com som original Fiat. E freios ABS e com direção hidráulica, rodas de liga leve mais 04 pneus novos.",
        extras: ["Segundo dono", "Aceitamos troca"],
    },
    {
        id: 5,
        brand: "Fiat",
        model: "Strada",
        version: "Freedom 1.4",
        year: 2020,
        modelYear: 2020,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Preto",
        image: "/car-suv.png",
        features: [
            "4X2",
            "Freios ABS",
            "Rodas Liga Leve",
            "4 Pneus Novos",
            "Direção Hidráulica",
            "Câmbio Manual",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo 4X2, com freios ABS e rodas de liga leve. e 04 pneus novos. Direção hidráulica com câmbio manual.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 6,
        brand: "Hyundai",
        model: "HB20S",
        version: "Sedan Comfort Plus 1.6",
        year: 2015,
        modelYear: 2014,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-sedan.png",
        features: [
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "Controle Som Volante",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de direção hidráulica, com rodas de liga leve. Controle de som no volante, travas e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 7,
        brand: "Chevrolet",
        model: "Prisma",
        version: "LTZ 1.4",
        year: 2014,
        modelYear: 2013,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Prata",
        image: "/car-sedan.png",
        features: [
            "Câmbio Automático",
            "Rodas Liga Leve",
            "Direção Hidráulica",
            "Ar Condicionado",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, com rodas de liga leve e direção hidráulica. Com ar condicionando quente e frio, com travas e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 8,
        brand: "Chevrolet",
        model: "Cruze",
        version: "LTZ Turbo 1.4",
        year: 2017,
        modelYear: 2016,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Preto",
        image: "/car-sedan.png",
        features: [
            "Câmbio Automático",
            "Rodas Liga Leve",
            "Direção Elétrica",
            "Freios ABS",
            "Retrovisor Elétrico",
            "Bancos Couro Ecológico",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, com rodas de liga leve e direção elétrica. Com freios abs, e retrovisor elétrico, com os bancos de couro ecológico.",
        extras: ["Segundo dono", "Aceitamos troca"],
    },
    {
        id: 9,
        brand: "Chevrolet",
        model: "Onix",
        version: "Hatch Active 1.4",
        year: 2017,
        modelYear: 2016,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Vermelho",
        image: "/car-hatchback.png",
        features: [
            "Direção Hidráulica",
            "Câmbio Manual",
            "Rodas Liga Diamantadas",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de direção hidráulica, com câmbio manual. Rodas de liga diamantadas, travas e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 10,
        brand: "Chevrolet",
        model: "Onix",
        version: "Sedan Plus 1.0 Turbo",
        year: 2022,
        modelYear: 2022,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Branco",
        image: "/car-sedan.png",
        features: [
            "Sensor Estacionamento",
            "Rodas Liga Leve",
            "Câmbio Automático",
            "Travas Elétricas",
            "Vidros Elétricos",
            "Kit Multimídia",
            "Controle Mídia Volante",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo com sensor de estacionamento, rodas de liga leve e câmbio automático. Trava e vidros elétricos, kit multimidia e controle de midia no volante.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 11,
        brand: "Chevrolet",
        model: "Tracker",
        version: "Premier 1.2 Turbo",
        year: 2022,
        modelYear: 2021,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Prata",
        image: "/car-suv.png",
        features: [
            "Câmbio Automático",
            "Direção Elétrica",
            "Freios ABS",
            "Controle Som Volante",
            "Bancos Couro Ecológico",
            "Rodas Liga Leve",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, direção elétrica e freios ABS. Com controle de som no volante, bancos em couro ecológico e rodas de liga leve.",
        extras: ["Único dono", "Aceitamos troca"],
    },
    {
        id: 12,
        brand: "Renault",
        model: "Duster",
        version: "Dakar 1.6",
        year: 2016,
        modelYear: 2016,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-suv.png",
        features: [
            "Câmbio Manual",
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "Bancos Couro Ecológico",
            "Computador Bordo",
            "Câmera de Ré",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, com direção hidráulica com rodas de liga leve. Com bancos em couro/ecológico, computador de bordo e direção de ré.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 13,
        brand: "Volkswagen",
        model: "Polo",
        version: "1.6",
        year: 2020,
        modelYear: 2019,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-hatchback.png",
        features: [
            "Câmbio Manual",
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "Freios ABS",
            "Ar Condicionado",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, com direção hidráulica com rodas de liga leve e freios Abs. Com ar condicionado, travas e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 14,
        brand: "Renault",
        model: "Captur",
        version: "Intense 1.6",
        year: 2020,
        modelYear: 2019,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Prata",
        image: "/car-suv.png",
        features: [
            "Câmbio Automático",
            "Direção Elétrica",
            "Rodas Diamantadas",
            "Câmera de Ré",
            "Freios ABS",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, direção elétrica. Rodas diamantadas, com camera de ré e freios Abs.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 15,
        brand: "Chevrolet",
        model: "Spin",
        version: "Activate 1.8",
        year: 2017,
        modelYear: 2017,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Preto",
        image: "/car-suv.png",
        features: [
            "Freios ABS",
            "Direção Hidráulica",
            "Câmbio Automático",
            "Retrovisores Elétricos",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo com freios Abs, direção hidráulica de câmbio automático. Retrovisores, travas e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 16,
        brand: "Fiat",
        model: "Grand Siena",
        version: "Essence 1.6",
        year: 2014,
        modelYear: 2014,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-sedan.png",
        features: [
            "Câmbio Manual",
            "Rodas Liga Leve",
            "Mídia 2Din Original",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, com rodas de liga leve e mídia 2Din original.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 17,
        brand: "Hyundai",
        model: "Creta",
        version: "Limited 1.0",
        year: 2022,
        modelYear: 2021,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Branco",
        image: "/car-suv.png",
        features: [
            "Câmbio Automático",
            "Computador Bordo",
            "Piloto Automático",
            "Rodas Liga Leve",
            "Sensor Estacionamento",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, com computador de bordo e piloto automático. Com rodas de liga leve e sensor de estacionamento.",
        extras: ["Segundo dono", "Aceitamos troca"],
    },
    {
        id: 18,
        brand: "Renault",
        model: "Kwid",
        version: "Zen 1.0",
        year: 2024,
        modelYear: 2023,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Branco",
        image: "/car-hatchback.png",
        features: [
            "Câmbio Manual",
            "Ar Condicionado",
            "Direção Hidráulica",
            "Desembaçador Traseiro",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, ar condicionado e direção hidráulica. Com desembaçador traseiro, trava e vidros elétricos.",
        extras: ["Único dono", "Aceitamos troca"],
    },
    {
        id: 19,
        brand: "Ford",
        model: "Ka",
        version: "SE Plus 1.5",
        year: 2024,
        modelYear: 2023,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Prata",
        image: "/car-hatchback.png",
        features: [
            "Câmbio Manual",
            "Ar Condicionado",
            "Direção Hidráulica",
            "Desembaçador Traseiro",
            "Travas Elétricas",
            "Vidros Elétricos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, ar condicionado e direção hidráulica. Com desembaçador traseiro, trava e vidros elétricos.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 20,
        brand: "Honda",
        model: "Fit",
        version: "LX 1.5",
        year: 2020,
        modelYear: 2020,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Automático",
        color: "Branco",
        image: "/car-hatchback.png",
        features: [
            "Câmbio Automático",
            "Freios ABS",
            "Direção Hidráulica",
            "4 Pneus Novos",
            "Rodas Liga Leve",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio automático, freios abs e direção hidráulica. Com 04 pneus novos e rodas de liga leve.",
        extras: ["Aceitamos troca"],
    },
    {
        id: 21,
        brand: "Fiat",
        model: "Idea",
        version: "Attract 1.4",
        year: 2016,
        modelYear: 2015,
        price: "Consulte",
        fuel: "Flex",
        km: "Consulte",
        transmission: "Manual",
        color: "Preto",
        image: "/car-hatchback.png",
        features: [
            "Câmbio Manual",
            "Ar Condicionado",
            "Direção Hidráulica",
            "Rodas Liga Leve",
            "4 Pneus Novos",
            "IPVA Pago",
            "Revisão em Dia",
        ],
        description:
            "Veículo de câmbio manual, ar condicionado e direção hidráulica. Com rodas de liga leve e 04 pneus novos.",
        extras: ["Segundo dono", "Aceitamos troca"],
    },
];
